### ISSUE TITLE
Tessel#wifiStatus method only returns partial data

### ISSUE THREAD

**Issue by ondreian** [tessel/cli#181]
I've been hacking on my Tessel to create a node-webkit application to make playing with Tessels a little more interesting, however I have run into considerable limitations with the current tessel module.

When using the tessel module programmatically an invoking  Tessel#wifiStatus only receives something like this:

```coffeescript
{"connected": 1, "ip": "12.10.100.10"}
```

however when you type 'tessel wifi -l', which also invokes Tessel#wifiStatus you get a more complete list of the current wifi state of the chip like this:

```
INFO Requesting wifi status...
Current network: NETGEAR06
Currently visible networks (7):
        NETGEAR06 (63/127)
        homenetwork1 (34/127)
        WaltonWifi (61/127)
        Saimaetwork1en (36/127)
        workzone (34/127)
        SBG6580F3 (59/127)
        NETGEAR09rk1en (33/127)
INFO Connected: 1
INFO Ip: 10.100.10.12
```
The majority of the info, like the list of networks and the network you're currently connected to gets passed into the `_recieveLogs` stream instead of the `_sendMessage` stream, and then is sent to the process.stdout, which never gets emitted or passed into any callbacks

As best as I can tell there is no documented method to glean this info from the Tessel without a good bit of hacking on the original tessel npm module.

The Tessel#checkWifi also provides valuable info about the current state of the tessel on the LAN, but there is no straightforward way of accessing this with the common api exposed to the developer as well.

I really feel like the cli and the actual programmatic invocation of commands on the Tessel should be as close to the same as possible as far as the information that is received from the Tessel and passed to the developer/program.

**Comment by johnnyman727** [comment]
After a quick investigation, it looks like [wifi_json](https://github.com/tessel/t1-firmware/blob/096e9561dcc15bd79c59bfbdb40647ef6269cd3d/src/tessel_wifi.c#L285) would need to call [`wlan_ioctl_get_scan_results`](https://github.com/tessel/t1-firmware/blob/096e9561dcc15bd79c59bfbdb40647ef6269cd3d/src/main.c#L234)

**Comment by jiahuang** [comment]
> When using the tessel module programmatically

You're referring to the tessel module on the actual board, not the CLI module running on a computer, right?

Last I recall, `wlan_ioctl_get_scan_results` sometimes... hangs forever when there are high network counts. Best way to expose this functionality through the onboard tessel module is probably to do the following:

1. Have a timer kick out after a certain amount scanning time. Probably make this an argument that the scan function can take.
2. Move the scanning out to a separate function that isn't on the USB message parsing code.
3. Add a `wifi.scan` command.

**Comment by ondreian** [comment]
I mean the CLI/Programmatic communication module (that communicates to the Tessel via USB)

The one that you install globally via NPM to talk to the tessel, it lets you query your USB ports for tessels that are connected and the like, but the actual programmatic commands being executed against an instance of a Tessel don't return the same information (such as the complete wifi list) as a comparable CLI command, even though they are both calling the same 

a short contrived example would be adding something like this to a short script on your localhost not via `tessel run` (assuming you have a tessel that can be found via USB)

```coffeescript
# require the CLI tools, this is not the same module embedded on the Tessel itself
tessel = require('tessel')
.
# find a device that is connected via USB to the localhost
tessel.findTessel {}, (err, device)->

  # check the wifi status of the found device
  device.wifiStatus (err, result)->
     console.log(result); # this will be {"connected": 1, "ip": "12.10.100.10"} or something 
```

however calling `tessel wifi -l` calls [this part of the bin](https://github.com/tessel/cli/blob/master/bin/tessel-wifi.js#L72-L83)

Which invokes the same Tessel#wifiStatus() method that outputs the lovely list of info that I mentioned above.

I appreciate you guys looking into this.

**Comment by johnnyman727** [comment]
Ah okay, I understand. I thought you were hoping to get a list of available networks on the Tessel but instead you'd like it available from the CLI API (which is actually a bit easier). I don't have time to make this change right now but I can make some suggestions: after `wifiStatus` is called, [the `logs` event](https://github.com/tessel/cli/blob/master/src/commands.js#L164-L178) will have to be monitored and results concatenated so it can be returned in the callback.

**Comment by ondreian** [comment]
I appreciate your advice on how to handle it, and realistic update. 

Considering the Tessel 2 is coming down the road (which I am excited to play with), I suppose I will set up a virtualbox for the T2 environment and just use that as a basis for my GUI for now.

Thanks again.

**Comment by johnnyman727** [comment]
:+1:
